# Generated by Django 3.0.7 on 2020-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('contact', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.EmailField(blank=True, max_length=255)),
                ('instagram', models.EmailField(blank=True, max_length=255)),
                ('telegram', models.EmailField(blank=True, max_length=255)),
                ('youtube', models.EmailField(blank=True, max_length=255)),
                ('twitter', models.EmailField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
